env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
tls:
  path_to_cert: "./config/certs/cert.pem"
  path_to_key: "./config/certs/key.pem"
  port: ":8082"
jwt:
  access_secret: "accessSecret"
  refresh_secret: "refreshSecret"
  access_token_ttl: 15m
  refresh_token_ttl: 168h